### ISSUE TITLE
LOD: revisit poison damage, and min/max lightning damage

### ISSUE THREAD

**Issue by mckyle099** [d2esrdb/d2esrdb.github.io#27]
now that we have LOD loaded we can verify a lot easier.

One thing is that the poison automods on necromancer shields is wrong

also the lightning damage on soj is wrong... well not wrong just not displaying right

**Comment by d2esrdb** [comment]
Adding to this, it seems like poison damage values aren't formatted right.
What is displayed in the docs is the value from files, but the real poison damage value can be calculated like this:
<value from file (min/max)>*<param value>/256 = real poison damage.

**Comment by d2esrdb** [comment]
didn't fix the soj issue because it doesn't use dmg-ltng, it uses ltng-min and ltng-max... idk I can't be bothered to fix it...
