### ISSUE TITLE
life/lvl is off by a factor of 8?

### ISSUE THREAD

**Issue by mckyle099** [d2esrdb/d2esrdb.github.io#39]
master of fire in es resurrected says 8/lvl on docs but 1/lvl in game

**Comment by d2esrdb** [comment]
Celestialray — 11/29/24, 7:20 AM
Adding to this, values that are based on character level are in 8ths, so if the param value is 8, it should say 1 per level. Example:
+8 to Energy (Based on Character Level)
Should be:
+1 to Energy per Level (Based on Character Level)
Or something like that.
Or keep it like the original vanilla text:
+ (0.5 per Character Level) 0-49 to Vitality (Based on Character Level)
This probably needs some hardcoded strings on your end though.
